### ISSUE TITLE
Empty changelogs are commited

### ISSUE THREAD

**Issue by Visne** [space-wizards/SS14.Changelog#1]
![image](https://user-images.githubusercontent.com/39844191/141801549-772d84f9-534b-448d-8470-bb17220e1ebb.png)

leads to

![image](https://user-images.githubusercontent.com/39844191/141801583-27f0b506-cb8c-4ca7-bbcb-2711126b427b.png)

**Comment by PJB3005** [comment]
Fixed by https://github.com/space-wizards/space-station-14/commit/2ef0089152478a33616e69250165604cdd13d7f5
